### ISSUE TITLE
How to use the Web Socket API

### ISSUE THREAD

**Issue by Flo2410** [Earthcomputer/pterodactyl_api#1]
Hello,  

I would like to know how to use the Web Socket API, as it is not documented anywhere. I figured out that I probably have to call `run_websocket_loop` but I cannot figure out what I should pass to it. 

Could you please help me?

**Comment by Earthcomputer** [comment]
Hi, the function you mention is documented in the source just like the rest of the API, it just didn't generate into docs.rs for some reason.

**Comment by Flo2410** [comment]
I figured it out with what I found in <https://github.com/ProtoTechMC/ProtoBot2>.
Especially looking at the dependencies, the web socket API is incompatible with a newer version of `async-tungstenite` then `0.20`  (I had `0.25.1` installed)

**Comment by Earthcomputer** [comment]
Okay, I will take a look at the outdated dependency, thanks for telling me :)

**Comment by Earthcomputer** [comment]
Hi, sorry for the late response. I have updated `async-tungstenite` and released 0.2.0
